id = "terrible-theme"
name = "Terrible Theme"
version = "0.0.2"
schema_version = 1
authors = ["Nooooaaaaah <nspielman96@gmail.com>"]
description = "A terrible theme for zed"
repository = "https://github.com/nooooaaaaah/terrible-zed"
